image: python:slim-buster

before_script:
  - apt update && apt install make -y
  - python -m pip install --upgrade -e .[dev]

stages:
  - test
  - build

run-test:
  stage: test
  script:
    - pytest -svv

build-docs:
  stage: build
  script:
    - make -C docs html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

