image: python:slim-bookworm

stages:
  - test-simple
  - test-simple-tox
  - build

run-tests-simple:
  stage: test-simple
  before_script:
    - apt update && apt install make git curl -y
    - python -m pip install --upgrade -e .[dev]
  script:
    - pytest -svv

run-test-tox-simple:
  stage: test-simple
  before_script:
    - apt update && apt install make git curl -y
    - curl https://pyenv.run | bash
    - |-
      cat << EOF >> ~/.bashrc
      export PYENV_ROOT="\$HOME/.pyenv"
      test -d "\$PYENV_ROOT/bin" && export PATH="\$PYENV_ROOT/bin:\$PATH"
      eval "\$(pyenv init -)"
      EOF
    - apt install build-essential python3-dev -y
    - |-
      apt install libreadline-dev \
        libncursesw5-dev \
        libssl-dev \
        libsqlite3-dev \
        tk-dev \
        libgdbm-dev \
        libc6-dev \
        libbz2-dev \
        libffi-dev \
        liblzma-dev -y
    - source ~/.bashrc
    - pyenv update
    - pyenv install 3.11 3.12
  script:
    - source ~/.bashrc
    - pyenv local 3.11 3.12
    - python -m pip install --upgrade -e .[dev]
    - python -m tox

build-docs:
  stage: build
  before_script:
    - apt update && apt install make git curl -y
    - python -m pip install --upgrade -e .[dev]
  script:
    - make -C docs html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week

